#!/usr/bin/env bash
#
# NOTE: This script was generated by an AI assistant (GitHub Copilot CLI).
#
# Generate a PNG for the .mmd file given as argument.
#
# Usage: ./build.sh <file.mmd>
#
# In addition, if the supplied file is a mindmap with top-level `id))…((`
# sections, it is automatically split into one PNG per level-1 section so
# that every L1 branch is rendered both as part of the global roadmap and
# on its own.
#
# Per-section PNGs are named:   <stem>__<N>_<slug>.png
# and are written next to the source file. The intermediate .mmd files used
# for rendering are emitted into a `.build/` cache directory.

set -euo pipefail

cd "$(dirname "$0")"

if [[ $# -ne 1 ]]; then
    echo "Usage: $0 <file.mmd>" >&2
    exit 2
fi

SRC="$1"

if [[ ! -f "$SRC" ]]; then
    echo "Error: file not found: $SRC" >&2
    exit 1
fi

if [[ "${SRC##*.}" != "mmd" ]]; then
    echo "Error: expected a .mmd file, got: $SRC" >&2
    exit 1
fi

if ! command -v mmdc >/dev/null 2>&1; then
    echo "Error: mmdc (mermaid-cli) is not installed." >&2
    echo "Install it with: npm install -g @mermaid-js/mermaid-cli" >&2
    exit 1
fi

WIDTH=2800
HEIGHT=1800
BG=white
CACHE_DIR=".build"

render() {
    local src="$1" dst="$2"
    echo "[build] $src -> $dst"
    mmdc -i "$src" -o "$dst" -w "$WIDTH" -H "$HEIGHT" -b "$BG" --quiet
}

# Render the supplied .mmd file.
SRC_DIR="$(dirname "$SRC")"
SRC_BASE="$(basename "$SRC")"
SRC_STEM="${SRC_BASE%.mmd}"
render "$SRC" "${SRC_DIR}/${SRC_STEM}.png"

# Auto-split the supplied file into per-section PNGs (if it has L1 sections).
mkdir -p "$CACHE_DIR"
SECTION_LIST="$(python3 - "$SRC" "$CACHE_DIR" <<'PY'
import re, sys, pathlib

src = pathlib.Path(sys.argv[1])
cache = pathlib.Path(sys.argv[2])
text = src.read_text(encoding="utf-8")

# Per-section color palette, indexed by section order in the file.
palette = [
    {"main": "#1f77b4", "l3": "#154360", "l3_stroke": "#0b3d66", "l4": "#5dade2"},
    {"main": "#2ca02c", "l3": "#145a32", "l3_stroke": "#14541a", "l4": "#58d68d"},
    {"main": "#ff7f0e", "l3": "#af601a", "l3_stroke": "#a04a00", "l4": "#f5b041"},
    {"main": "#d62728", "l3": "#78281f", "l3_stroke": "#7a1415", "l4": "#ec7063"},
]

lines = text.splitlines()

# Find the `mindmap` line, then the `root((...))` line. Everything after the
# root, separated by top-level `id))...((` markers, is a section.
try:
    mindmap_idx = next(i for i, l in enumerate(lines) if l.strip() == "mindmap")
    root_idx = next(i for i in range(mindmap_idx + 1, len(lines))
                    if lines[i].lstrip().startswith("root("))
except StopIteration:
    sys.exit(0)

body = lines[root_idx + 1:]

# Indent of section headers (first non-blank line after root).
section_indent = None
for l in body:
    if l.strip():
        section_indent = len(l) - len(l.lstrip(" "))
        break
if section_indent is None:
    sys.exit(0)

section_re = re.compile(r"^\s*id\)\)(.+?)\(\(\s*$")

sections = []  # list of (header_line, content_lines)
current = None
for l in body:
    indent = len(l) - len(l.lstrip(" "))
    m = section_re.match(l)
    if m and indent == section_indent:
        if current is not None:
            sections.append(current)
        current = [l]
    elif current is not None:
        current.append(l)
if current is not None:
    sections.append(current)


def slugify(label: str) -> str:
    # Drop everything except ASCII letters, digits, spaces.
    s = re.sub(r"[^A-Za-z0-9 ]+", " ", label)
    return "_".join(s.lower().split())[:60] or "section"


for idx, lines_in_section in enumerate(sections):
    header = lines_in_section[0]
    label = section_re.match(header).group(1).strip()
    slug = slugify(label)
    colors = palette[idx % len(palette)]

    frontmatter = f"""---
config:
  theme: base
  themeVariables:
    cScale0: '#34495e'
    cScale1: '{colors["main"]}'
    cScaleLabel0: '#ffffff'
    cScaleLabel1: '#ffffff'
  themeCSS: |
    g.section-0 rect.basic.label-container:not([rx]) {{ fill: {colors["l3"]} !important; stroke: {colors["l3_stroke"]} !important; stroke-width: 1.5px !important; }}
    g.section-0 rect.basic.label-container[rx] {{ fill: {colors["l4"]} !important; stroke: {colors["main"]} !important; stroke-width: 1.5px !important; }}
---

mindmap
  root((SEAPATH))
""" + "\n".join(lines_in_section) + "\n"

    out = cache / f"{src.stem}__{idx}_{slug}.mmd"
    out.write_text(frontmatter, encoding="utf-8")
    print(out)
PY
)"

if [[ -n "$SECTION_LIST" ]]; then
    while IFS= read -r section_mmd; do
        [[ -f "$section_mmd" ]] || continue
        name="$(basename "$section_mmd" .mmd)"
        render "$section_mmd" "${SRC_DIR}/${name}.png"
    done <<<"$SECTION_LIST"
fi

echo "[build] done"
